Repository jeffreytse/zsh-vi-mode, pull requests merged in 2021-11, with the labels that each got.

#138 feat: support home, end and delete keys (#134)
  zsh-vi-mode.zsh
Labels: enhancement

#139 Update link to zinit project
  README.md
Labels: documentation

#140 Add note about timeouts in surround guide
  README.md
Labels: documentation

#143 Escape ZVM_VI_EDITOR
  zsh-vi-mode.zsh
Labels: bug
